BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE system_settings (
      setting_key VARCHAR2(80) PRIMARY KEY,
      setting_value CLOB CHECK (setting_value IS JSON),
      updated_by NUMBER,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE '
    CREATE TABLE settings_history (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      setting_key VARCHAR2(80) NOT NULL,
      old_value CLOB,
      new_value CLOB,
      changed_by NUMBER,
      changed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_settings_history_key_time ON settings_history(setting_key, changed_at)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN RAISE; END IF;
END;
/
