import { getConnection } from "../config/database";
import { HttpError } from "../utils/httpError";
import { getInfrastructureServices } from "./infrastructureServices.service";

type AgentStatus = "online" | "slow" | "offline" | "unknown";

type ClientAgentHeartbeatInput = {
  clientId?: unknown;
  hostname?: unknown;
  ipAddress?: unknown;
  department?: unknown;
  block?: unknown;
  agentVersion?: unknown;
  status?: unknown;
  latencyMs?: unknown;
  cpuUsage?: unknown;
  memoryUsage?: unknown;
  diskUsage?: unknown;
  lastBootTime?: unknown;
};

type ClientAgentServiceCheckInput = {
  clientId?: unknown;
  hostname?: unknown;
  checks?: unknown;
};

type ClientAgentServiceCheck = {
  serviceKey?: unknown;
  serviceName?: unknown;
  targetUrl?: unknown;
  status?: unknown;
  latencyMs?: unknown;
  dnsMs?: unknown;
  errorMessage?: unknown;
  checkedAt?: unknown;
};

const slowLatencyThresholdMs = 500;
const highUsageThresholdPercent = 85;
const criticalUsageThresholdPercent = 90;
const onlineWindowMs = 2 * 60 * 1000;
const offlineWindowMs = 5 * 60 * 1000;

function cleanString(value: unknown, max = 500) {
  return String(value || "").trim().slice(0, max);
}

function optionalNumber(value: unknown, label: string) {
  if (value === null || value === undefined || value === "") return null;
  const number = Number(value);
  if (!Number.isFinite(number) || number < 0) throw new HttpError(400, `Invalid ${label}.`);
  return Math.round(number * 100) / 100;
}

function optionalPercent(value: unknown, label: string) {
  const number = optionalNumber(value, label);
  if (number === null) return null;
  if (number > 100) throw new HttpError(400, `Invalid ${label}.`);
  return number;
}

function optionalDate(value: unknown, label: string) {
  if (!value) return null;
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) throw new HttpError(400, `Invalid ${label}.`);
  return date;
}

function normalizeStatus(value: unknown) {
  const status = cleanString(value, 30).toLowerCase().replaceAll(" ", "_");
  if (status === "online" || status === "slow" || status === "offline" || status === "cannot_verify") return status;
  throw new HttpError(400, "Invalid service check status.");
}

function normalizeHeartbeat(input: ClientAgentHeartbeatInput) {
  const clientId = cleanString(input.clientId, 160);
  const hostname = cleanString(input.hostname, 255);
  if (!clientId && !hostname) throw new HttpError(400, "clientId or hostname is required.");
  const status = cleanString(input.status, 30).toLowerCase();
  return {
    clientId: clientId || hostname,
    hostname: hostname || clientId,
    ipAddress: cleanString(input.ipAddress, 80) || null,
    department: cleanString(input.department, 160) || null,
    block: cleanString(input.block, 160) || null,
    agentVersion: cleanString(input.agentVersion, 40) || null,
    status: ["online", "slow", "offline", "unknown"].includes(status) ? status : "online",
    latencyMs: optionalNumber(input.latencyMs, "latency"),
    cpuUsage: optionalPercent(input.cpuUsage, "CPU usage"),
    memoryUsage: optionalPercent(input.memoryUsage, "memory usage"),
    diskUsage: optionalPercent(input.diskUsage, "disk usage"),
    lastBootTime: optionalDate(input.lastBootTime, "lastBootTime")
  };
}

export async function ensureClientAgentStatusTable(connection: any) {
  const result = await connection.execute(`SELECT COUNT(*) AS count FROM user_tables WHERE table_name = 'CLIENT_AGENT_STATUS'`);
  const exists = Number(((result.rows || [])[0] as { COUNT?: number })?.COUNT || 0) > 0;
  if (!exists) {
    await connection.execute(
      `CREATE TABLE client_agent_status (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id VARCHAR2(160) NOT NULL,
        hostname VARCHAR2(255),
        ip_address VARCHAR2(80),
        department VARCHAR2(160),
        block VARCHAR2(160),
        agent_version VARCHAR2(40),
        status VARCHAR2(30),
        latency_ms NUMBER,
        cpu_usage NUMBER(7,2),
        memory_usage NUMBER(7,2),
        disk_usage NUMBER(7,2),
        last_boot_time TIMESTAMP,
        last_seen_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )`
    );
    await connection.execute(`CREATE UNIQUE INDEX uq_client_agent_status_client ON client_agent_status(client_id)`);
    await connection.execute(`CREATE INDEX idx_client_agent_status_seen ON client_agent_status(last_seen_at)`);
    await connection.commit();
    return;
  }

  const columnsResult = await connection.execute(`SELECT column_name FROM user_tab_columns WHERE table_name = 'CLIENT_AGENT_STATUS'`);
  const columns = new Set(((columnsResult.rows || []) as Array<{ COLUMN_NAME: string }>).map((row) => row.COLUMN_NAME));
  const additions: Array<[string, string]> = [
    ["AGENT_VERSION", "agent_version VARCHAR2(40)"],
    ["CPU_USAGE", "cpu_usage NUMBER(7,2)"],
    ["MEMORY_USAGE", "memory_usage NUMBER(7,2)"],
    ["DISK_USAGE", "disk_usage NUMBER(7,2)"],
    ["LAST_BOOT_TIME", "last_boot_time TIMESTAMP"],
    ["UPDATED_AT", "updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL"]
  ];
  for (const [column, definition] of additions) {
    if (!columns.has(column)) await connection.execute(`ALTER TABLE client_agent_status ADD (${definition})`);
  }
  await connection.commit();
}

async function ensureClientAgentServiceHistoryTable(connection: any) {
  const result = await connection.execute(`SELECT COUNT(*) AS count FROM user_tables WHERE table_name = 'CLIENT_AGENT_SERVICE_HISTORY'`);
  const exists = Number(((result.rows || [])[0] as { COUNT?: number })?.COUNT || 0) > 0;
  if (!exists) {
    await connection.execute(
      `CREATE TABLE client_agent_service_history (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        client_id VARCHAR2(160) NOT NULL,
        hostname VARCHAR2(255),
        service_key VARCHAR2(120) NOT NULL,
        service_name VARCHAR2(160) NOT NULL,
        target_url VARCHAR2(1000),
        status VARCHAR2(30) NOT NULL,
        latency_ms NUMBER,
        dns_ms NUMBER,
        error_message VARCHAR2(1000),
        checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )`
    );
    await connection.execute(`CREATE INDEX idx_client_agent_svc_hist_client ON client_agent_service_history(client_id, checked_at)`);
    await connection.execute(`CREATE INDEX idx_client_agent_svc_hist_service ON client_agent_service_history(service_key, checked_at)`);
    await connection.commit();
  }
}

function normalizeServiceChecks(input: ClientAgentServiceCheckInput) {
  const clientId = cleanString(input.clientId, 160);
  const hostname = cleanString(input.hostname, 255);
  if (!clientId && !hostname) throw new HttpError(400, "clientId or hostname is required.");
  const checks = Array.isArray(input.checks) ? input.checks as ClientAgentServiceCheck[] : [];
  if (!checks.length) throw new HttpError(400, "At least one service check is required.");
  return {
    clientId: clientId || hostname,
    hostname: hostname || clientId,
    checks: checks.map((check) => {
      const serviceKey = cleanString(check.serviceKey, 120);
      const serviceName = cleanString(check.serviceName, 160);
      if (!serviceKey || !serviceName) throw new HttpError(400, "serviceKey and serviceName are required.");
      return {
        serviceKey,
        serviceName,
        targetUrl: cleanString(check.targetUrl, 1000) || null,
        status: normalizeStatus(check.status),
        latencyMs: optionalNumber(check.latencyMs, "latency"),
        dnsMs: optionalNumber(check.dnsMs, "DNS time"),
        errorMessage: cleanString(check.errorMessage, 1000) || null,
        checkedAt: optionalDate(check.checkedAt, "checkedAt") || new Date()
      };
    })
  };
}

export async function saveClientAgentHeartbeat(input: ClientAgentHeartbeatInput) {
  const values = normalizeHeartbeat(input);
  const connection = await getConnection();
  try {
    await ensureClientAgentStatusTable(connection);
    await connection.execute(
      `MERGE INTO client_agent_status target
       USING (SELECT :clientId AS client_id FROM dual) source
       ON (target.client_id = source.client_id)
       WHEN MATCHED THEN UPDATE SET
         hostname = :hostname,
         ip_address = :ipAddress,
         department = :department,
         block = :block,
         agent_version = :agentVersion,
         status = :status,
         latency_ms = :latencyMs,
         cpu_usage = :cpuUsage,
         memory_usage = :memoryUsage,
         disk_usage = :diskUsage,
         last_boot_time = :lastBootTime,
         last_seen_at = SYSTIMESTAMP,
         updated_at = SYSTIMESTAMP
       WHEN NOT MATCHED THEN INSERT (
         client_id, hostname, ip_address, department, block, agent_version,
         status, latency_ms, cpu_usage, memory_usage, disk_usage,
         last_boot_time, last_seen_at, created_at, updated_at
       ) VALUES (
         :clientId, :hostname, :ipAddress, :department, :block, :agentVersion,
         :status, :latencyMs, :cpuUsage, :memoryUsage, :diskUsage,
         :lastBootTime, SYSTIMESTAMP, SYSTIMESTAMP, SYSTIMESTAMP
       )`,
      values
    );
    await connection.commit();
    return { ok: true, data: { clientId: values.clientId, status: values.status } };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    await connection.close();
  }
}

export async function saveClientAgentServiceChecks(input: ClientAgentServiceCheckInput) {
  const values = normalizeServiceChecks(input);
  const connection = await getConnection();
  try {
    await ensureClientAgentServiceHistoryTable(connection);
    for (const check of values.checks) {
      await connection.execute(
        `INSERT INTO client_agent_service_history (
          client_id, hostname, service_key, service_name, target_url,
          status, latency_ms, dns_ms, error_message, checked_at, created_at
        ) VALUES (
          :clientId, :hostname, :serviceKey, :serviceName, :targetUrl,
          :status, :latencyMs, :dnsMs, :errorMessage, :checkedAt, SYSTIMESTAMP
        )`,
        {
          clientId: values.clientId,
          hostname: values.hostname,
          ...check
        }
      );
    }
    await connection.commit();
    return { ok: true, data: { clientId: values.clientId, checks: values.checks.length } };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    await connection.close();
  }
}

function rowTime(value: unknown) {
  const time = new Date(String(value)).getTime();
  return Number.isFinite(time) ? time : 0;
}

function hasHighUsage(row: Record<string, any>, threshold = highUsageThresholdPercent) {
  return [row.CPU_USAGE, row.MEMORY_USAGE, row.DISK_USAGE].some((value) => value !== null && value !== undefined && Number(value) >= threshold);
}

function classifyAgent(row: Record<string, any>, now = Date.now()): AgentStatus {
  const lastSeen = rowTime(row.LAST_SEEN_AT);
  if (!lastSeen) return "unknown";
  const age = now - lastSeen;
  if (age > offlineWindowMs) return "offline";
  if ((row.LATENCY_MS !== null && row.LATENCY_MS !== undefined && Number(row.LATENCY_MS) > slowLatencyThresholdMs) || hasHighUsage(row)) return "slow";
  if (age <= onlineWindowMs) return "online";
  return "unknown";
}

function isCriticalSlow(row: Record<string, any>) {
  return (row.LATENCY_MS !== null && row.LATENCY_MS !== undefined && Number(row.LATENCY_MS) > slowLatencyThresholdMs) || hasHighUsage(row, criticalUsageThresholdPercent);
}

export async function getClientAgentSummary() {
  const connection = await getConnection();
  try {
    await ensureClientAgentStatusTable(connection);
    const result = await connection.execute(
      `SELECT client_id, hostname, ip_address, department, block, agent_version,
              status, latency_ms, cpu_usage, memory_usage, disk_usage,
              last_boot_time, last_seen_at, created_at, updated_at
       FROM client_agent_status`
    );
    const rows = (result.rows || []) as Array<Record<string, any>>;
    const now = Date.now();
    const classified = rows.map((row) => ({ row, status: classifyAgent(row, now) }));
    const onlineOrSlow = classified.filter((item) => item.status === "online" || item.status === "slow");
    const responseValues = onlineOrSlow
      .map((item) => item.row.LATENCY_MS)
      .filter((value): value is number => value !== null && value !== undefined)
      .map(Number);
    const offlineClients = classified.filter((item) => item.status === "offline").length;
    const criticalSlowClients = classified.filter((item) => item.status === "slow" && isCriticalSlow(item.row)).length;
    return {
      data: {
        totalClientPcs: rows.length,
        agentVerifiedOnline: classified.filter((item) => item.status === "online").length,
        slowClients: classified.filter((item) => item.status === "slow").length,
        offlineClients,
        dnsFailed: 0,
        cannotVerifyBrowserChecks: 0,
        averageClientResponseTimeMs: responseValues.length ? Math.round(responseValues.reduce((sum, value) => sum + value, 0) / responseValues.length) : null,
        activeIncidents: offlineClients + criticalSlowClients
      }
    };
  } finally {
    await connection.close();
  }
}

function rangeToInterval(range: unknown) {
  if (range === "7d") return "7";
  if (range === "30d") return "30";
  return "1";
}

function mapServiceHistoryRow(row: Record<string, any>) {
  return {
    id: Number(row.ID),
    clientId: row.CLIENT_ID || "",
    hostname: row.HOSTNAME || "",
    serviceKey: row.SERVICE_KEY || "",
    serviceName: row.SERVICE_NAME || "",
    targetUrl: row.TARGET_URL || "",
    status: row.STATUS || "",
    latencyMs: row.LATENCY_MS === null || row.LATENCY_MS === undefined ? null : Number(row.LATENCY_MS),
    dnsMs: row.DNS_MS === null || row.DNS_MS === undefined ? null : Number(row.DNS_MS),
    errorMessage: row.ERROR_MESSAGE || "",
    checkedAt: row.CHECKED_AT,
    createdAt: row.CREATED_AT
  };
}

export async function getClientAgentServiceHistory(filters: { clientId?: unknown; range?: unknown } = {}) {
  const connection = await getConnection();
  try {
    await ensureClientAgentServiceHistoryTable(connection);
    const clientId = cleanString(filters.clientId, 160);
    const binds: Record<string, unknown> = {};
    const where = [`checked_at >= SYSTIMESTAMP - INTERVAL '${rangeToInterval(filters.range)}' DAY`];
    if (clientId) {
      where.push(`client_id = :clientId`);
      binds.clientId = clientId;
    }
    const result = await connection.execute(
      `SELECT id, client_id, hostname, service_key, service_name, target_url,
              status, latency_ms, dns_ms, error_message, checked_at, created_at
       FROM client_agent_service_history
       WHERE ${where.join(" AND ")}
       ORDER BY checked_at ASC`,
      binds
    );
    return { data: ((result.rows || []) as Array<Record<string, any>>).map(mapServiceHistoryRow) };
  } finally {
    await connection.close();
  }
}

export async function getClientAgentServices() {
  const configured = await getInfrastructureServices();
  const hpepIntranet = configured.data.find((service) => service.id === "hpep-intranet");
  const services = configured.data
    .filter((service) => service.monitoringEnabled && service.url && service.url !== "internal://network-health")
    .map((service) => ({
      serviceKey: service.id === "hpep-intranet" || service.id === "bhel-webmail" ? service.id : `custom-${service.id}`,
      serviceName: service.name,
      targetUrl: service.url
    }));
  const serviceList = [
    { serviceKey: "client-internet", serviceName: "Internet", targetUrl: "https://www.google.com/generate_204" },
    { serviceKey: "client-intranet", serviceName: "Intranet", targetUrl: hpepIntranet?.url || "" },
    { serviceKey: "client-backend-api", serviceName: "Backend API", targetUrl: "/health" },
    { serviceKey: "google-service", serviceName: "Google", targetUrl: "https://www.google.com/generate_204" },
    ...services
  ];
  const uniqueServices = new Map(serviceList.map((service) => [service.serviceKey, service]));
  return {
    data: Array.from(uniqueServices.values())
  };
}
