import { getConnection } from "../config/database";
import { getClientAgentSummary } from "./clientAgent.service";
import type { JwtPayload } from "../types/auth";
import { HttpError } from "../utils/httpError";

type ClientConnectivityStatus =
  | "ONLINE"
  | "SLOW"
  | "OFFLINE"
  | "DNS_FAILED"
  | "CERTIFICATE_ERROR"
  | "PROXY_BLOCKED"
  | "CANNOT_VERIFY";

type ConnectivitySource = "BROWSER_CHECK" | "OPSCENTER_AGENT" | "BACKEND_VERIFIED";

type SaveClientConnectivityInput = {
  clientId?: unknown;
  hostname?: unknown;
  ipAddress?: unknown;
  userId?: unknown;
  department?: unknown;
  block?: unknown;
  checkedFrom?: unknown;
  source?: unknown;
  serviceName?: unknown;
  serviceType?: unknown;
  serviceUrl?: unknown;
  targetUrl?: unknown;
  status?: unknown;
  responseTimeMs?: unknown;
  packetLoss?: unknown;
  dnsStatus?: unknown;
  errorReason?: unknown;
  errorMessage?: unknown;
  checkedAt?: unknown;
  browserInfo?: unknown;
  clientIp?: unknown;
};

type ClientConnectivityFilters = {
  user?: unknown;
  source?: unknown;
  serviceName?: unknown;
  status?: unknown;
  role?: unknown;
  serviceType?: unknown;
  department?: unknown;
  block?: unknown;
  range?: unknown;
  dateFrom?: unknown;
  dateTo?: unknown;
};

const allowedStatuses = new Set<ClientConnectivityStatus>([
  "ONLINE", "SLOW", "OFFLINE", "DNS_FAILED", "CERTIFICATE_ERROR", "PROXY_BLOCKED", "CANNOT_VERIFY"
]);
const allowedSources = new Set<ConnectivitySource>(["BROWSER_CHECK", "OPSCENTER_AGENT", "BACKEND_VERIFIED"]);

const requiredColumns: Array<[string, string]> = [
  ["CLIENT_ID", "client_id VARCHAR2(160)"],
  ["HOSTNAME", "hostname VARCHAR2(255)"],
  ["IP_ADDRESS", "ip_address VARCHAR2(80)"],
  ["REPORTED_USER_ID", "reported_user_id VARCHAR2(160)"],
  ["DEPARTMENT", "department VARCHAR2(160)"],
  ["BLOCK", "block VARCHAR2(160)"],
  ["SOURCE", "source VARCHAR2(40) DEFAULT 'BROWSER_CHECK' NOT NULL"],
  ["SERVICE_URL", "service_url VARCHAR2(1000)"],
  ["PACKET_LOSS", "packet_loss NUMBER(7,2)"],
  ["DNS_STATUS", "dns_status VARCHAR2(40)"],
  ["ERROR_REASON", "error_reason VARCHAR2(1000)"]
];

async function ensureClientConnectivityHistoryTable(connection: any) {
  const result = await connection.execute(`SELECT COUNT(*) AS count FROM user_tables WHERE table_name = 'CLIENT_CONNECTIVITY_HISTORY'`);
  const exists = Number(((result.rows || [])[0] as { COUNT?: number })?.COUNT || 0) > 0;
  if (!exists) {
    await connection.execute(
      `CREATE TABLE client_connectivity_history (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER,
        username VARCHAR2(160),
        user_role VARCHAR2(40),
        client_id VARCHAR2(160),
        hostname VARCHAR2(255),
        ip_address VARCHAR2(80),
        reported_user_id VARCHAR2(160),
        department VARCHAR2(160),
        block VARCHAR2(160),
        checked_from VARCHAR2(80) DEFAULT 'Browser Check' NOT NULL,
        source VARCHAR2(40) DEFAULT 'BROWSER_CHECK' NOT NULL,
        service_name VARCHAR2(160) NOT NULL,
        service_type VARCHAR2(60),
        service_url VARCHAR2(1000),
        target_url VARCHAR2(500),
        status VARCHAR2(30) NOT NULL,
        response_time_ms NUMBER,
        packet_loss NUMBER(7,2),
        dns_status VARCHAR2(40),
        error_reason VARCHAR2(1000),
        browser_info VARCHAR2(1000),
        client_ip VARCHAR2(80),
        error_message VARCHAR2(1000),
        checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )`
    );
    await connection.execute(`CREATE INDEX idx_client_conn_hist_user_time ON client_connectivity_history(user_id, checked_at)`);
    await connection.execute(`CREATE INDEX idx_client_conn_hist_filters ON client_connectivity_history(source, status, service_name, checked_at)`);
    await connection.commit();
    return;
  }

  const columnsResult = await connection.execute(`SELECT column_name FROM user_tab_columns WHERE table_name = 'CLIENT_CONNECTIVITY_HISTORY'`);
  const columns = new Set(((columnsResult.rows || []) as Array<{ COLUMN_NAME: string }>).map((row) => row.COLUMN_NAME));
  const legacyColumns: Array<[string, string]> = [
    ["CHECKED_FROM", "checked_from VARCHAR2(80) DEFAULT 'Browser Check' NOT NULL"],
    ["CREATED_AT", "created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL"]
  ];
  for (const [column, definition] of [...legacyColumns, ...requiredColumns]) {
    if (!columns.has(column)) await connection.execute(`ALTER TABLE client_connectivity_history ADD ${definition}`);
  }
  await connection.commit();
}

function cleanString(value: unknown, max = 500) {
  return String(value || "").trim().slice(0, max);
}

function normalizeStatus(value: unknown): ClientConnectivityStatus {
  const status = cleanString(value, 30).toUpperCase().replaceAll(" ", "_") as ClientConnectivityStatus;
  if (!allowedStatuses.has(status)) throw new HttpError(400, "Invalid client connectivity status.");
  return status;
}

function normalizeSource(input: SaveClientConnectivityInput): ConnectivitySource {
  const explicit = cleanString(input.source, 40).toUpperCase().replaceAll(" ", "_") as ConnectivitySource;
  if (explicit && allowedSources.has(explicit)) return explicit;
  const checkedFrom = cleanString(input.checkedFrom, 80).toLowerCase();
  if (checkedFrom.includes("agent")) return "OPSCENTER_AGENT";
  if (checkedFrom.includes("backend") || checkedFrom.includes("server")) return "BACKEND_VERIFIED";
  return "BROWSER_CHECK";
}

function normalizeCheckedAt(value: unknown) {
  if (!value) return new Date();
  const date = new Date(String(value));
  if (Number.isNaN(date.getTime())) throw new HttpError(400, "Invalid checkedAt timestamp.");
  return date;
}

function optionalNumber(value: unknown, label: string) {
  if (value === null || value === undefined || value === "") return null;
  const number = Number(value);
  if (!Number.isFinite(number) || number < 0) throw new HttpError(400, `Invalid ${label}.`);
  return Math.round(number * 100) / 100;
}

function normalizeSaveInput(input: SaveClientConnectivityInput) {
  const serviceName = cleanString(input.serviceName, 160);
  if (!serviceName) throw new HttpError(400, "Service name is required.");
  const status = normalizeStatus(input.status);
  const source = normalizeSource(input);
  if (source !== "BROWSER_CHECK" && status === "CANNOT_VERIFY") {
    throw new HttpError(400, "Agent and backend reports must provide a confirmed status.");
  }
  const targetUrl = cleanString(input.serviceUrl ?? input.targetUrl, 1000) || null;
  const errorReason = cleanString(input.errorReason ?? input.errorMessage, 1000) || null;
  return {
    clientId: cleanString(input.clientId, 160) || null,
    hostname: cleanString(input.hostname, 255) || null,
    ipAddress: cleanString(input.ipAddress ?? input.clientIp, 80) || null,
    reportedUserId: cleanString(input.userId, 160) || null,
    department: cleanString(input.department, 160) || null,
    block: cleanString(input.block, 160) || null,
    checkedFrom: cleanString(input.checkedFrom, 80) || (source === "OPSCENTER_AGENT" ? "OpsCenter Agent" : source === "BACKEND_VERIFIED" ? "Backend Verified" : "Browser Check"),
    source,
    serviceName,
    serviceType: cleanString(input.serviceType, 60).toUpperCase().replaceAll(" ", "_") || "CUSTOM_LOCAL_SERVICE",
    serviceUrl: targetUrl,
    targetUrl,
    status,
    responseTimeMs: optionalNumber(input.responseTimeMs, "response time"),
    packetLoss: optionalNumber(input.packetLoss, "packet loss"),
    dnsStatus: cleanString(input.dnsStatus, 40).toLowerCase() || null,
    errorReason,
    checkedAt: normalizeCheckedAt(input.checkedAt),
    browserInfo: cleanString(input.browserInfo, 1000) || null
  };
}

function mapRow(row: Record<string, any>) {
  const source = (row.SOURCE || (String(row.CHECKED_FROM || "").toLowerCase().includes("agent") ? "OPSCENTER_AGENT" : "BROWSER_CHECK")) as ConnectivitySource;
  return {
    id: Number(row.ID),
    userId: Number(row.USER_ID) || null,
    reportedUserId: row.REPORTED_USER_ID || "",
    username: row.USERNAME || "",
    userRole: row.USER_ROLE || "",
    clientId: row.CLIENT_ID || "",
    hostname: row.HOSTNAME || "",
    ipAddress: row.IP_ADDRESS || row.CLIENT_IP || "",
    department: row.DEPARTMENT || "",
    block: row.BLOCK || "",
    checkedFrom: row.CHECKED_FROM || "Browser Check",
    source,
    sourceLabel: source === "OPSCENTER_AGENT" ? "Agent Verified" : source === "BACKEND_VERIFIED" ? "Backend Verified" : "Browser Check",
    serviceName: row.SERVICE_NAME,
    serviceType: row.SERVICE_TYPE || "",
    serviceUrl: row.SERVICE_URL || row.TARGET_URL || "",
    targetUrl: row.TARGET_URL || row.SERVICE_URL || "",
    status: row.STATUS,
    responseTimeMs: row.RESPONSE_TIME_MS === null || row.RESPONSE_TIME_MS === undefined ? null : Number(row.RESPONSE_TIME_MS),
    packetLoss: row.PACKET_LOSS === null || row.PACKET_LOSS === undefined ? null : Number(row.PACKET_LOSS),
    dnsStatus: row.DNS_STATUS || "",
    errorReason: row.ERROR_REASON || row.ERROR_MESSAGE || "",
    browserInfo: row.BROWSER_INFO || "",
    checkedAt: row.CHECKED_AT,
    createdAt: row.CREATED_AT
  };
}

function addFilters(where: string[], binds: Record<string, unknown>, filters: ClientConnectivityFilters) {
  const textFilters: Array<[unknown, string, string, number]> = [
    [filters.user, "username", "userFilter", 160],
    [filters.serviceName, "service_name", "serviceNameFilter", 160],
    [filters.department, "department", "departmentFilter", 160],
    [filters.block, "block", "blockFilter", 160]
  ];
  for (const [value, column, bind, max] of textFilters) {
    const cleaned = cleanString(value, max);
    if (cleaned) {
      where.push(`LOWER(${column}) LIKE LOWER(:${bind})`);
      binds[bind] = `%${cleaned}%`;
    }
  }
  const status = cleanString(filters.status, 30).toUpperCase().replaceAll(" ", "_");
  if (status && allowedStatuses.has(status as ClientConnectivityStatus)) {
    where.push(`status = :statusFilter`);
    binds.statusFilter = status;
  }
  const source = cleanString(filters.source, 40).toUpperCase().replaceAll(" ", "_");
  if (source && allowedSources.has(source as ConnectivitySource)) {
    where.push(`source = :sourceFilter`);
    binds.sourceFilter = source;
  }
  const serviceType = cleanString(filters.serviceType, 60).toUpperCase().replaceAll(" ", "_");
  if (serviceType) {
    where.push(`service_type = :serviceTypeFilter`);
    binds.serviceTypeFilter = serviceType;
  }
  const role = cleanString(filters.role, 40).toLowerCase();
  if (role && ["admin", "engineer", "employee"].includes(role)) {
    where.push(`LOWER(user_role) = :roleFilter`);
    binds.roleFilter = role;
  }
  if (!filters.dateFrom && !filters.dateTo) {
    const range = cleanString(filters.range, 10).toLowerCase();
    if (range === "7d") where.push(`checked_at >= SYSTIMESTAMP - INTERVAL '7' DAY`);
    else if (range === "30d") where.push(`checked_at >= SYSTIMESTAMP - INTERVAL '30' DAY`);
    else where.push(`checked_at >= SYSTIMESTAMP - INTERVAL '1' DAY`);
  }
  if (filters.dateFrom) {
    binds.dateFrom = normalizeCheckedAt(filters.dateFrom);
    where.push(`checked_at >= :dateFrom`);
  }
  if (filters.dateTo) {
    binds.dateTo = normalizeCheckedAt(filters.dateTo);
    where.push(`checked_at <= :dateTo`);
  }
}

async function queryHistory(filters: ClientConnectivityFilters = {}, userId?: number) {
  const connection = await getConnection();
  try {
    await ensureClientConnectivityHistoryTable(connection);
    const where: string[] = [];
    const binds: Record<string, unknown> = {};
    if (userId) {
      where.push(`user_id = :authenticatedUserId`);
      binds.authenticatedUserId = userId;
    }
    addFilters(where, binds, filters);
    const whereClause = where.length ? `WHERE ${where.join(" AND ")}` : "";
    const result = await connection.execute(
      `SELECT * FROM client_connectivity_history ${whereClause}
       ORDER BY checked_at DESC FETCH FIRST 100000 ROWS ONLY`,
      binds
    );
    return ((result.rows || []) as Array<Record<string, any>>).map(mapRow);
  } finally {
    await connection.close();
  }
}

export async function saveClientConnectivityHistory(input: SaveClientConnectivityInput, user: JwtPayload, fallbackClientIp?: string) {
  const values = normalizeSaveInput(input);
  const connection = await getConnection();
  try {
    await ensureClientConnectivityHistoryTable(connection);
    await connection.execute(
      `INSERT INTO client_connectivity_history (
        user_id, username, user_role, client_id, hostname, ip_address, reported_user_id,
        department, block, checked_from, source, service_name, service_type, service_url,
        target_url, status, response_time_ms, packet_loss, dns_status, error_reason,
        checked_at, browser_info, client_ip, error_message
      ) VALUES (
        :authenticatedUserId, :username, :userRole, :clientId, :hostname, :ipAddress, :reportedUserId,
        :department, :block, :checkedFrom, :source, :serviceName, :serviceType, :serviceUrl,
        :targetUrl, :status, :responseTimeMs, :packetLoss, :dnsStatus, :errorReason,
        :checkedAt, :browserInfo, :clientIp, :errorMessage
      )`,
      {
        authenticatedUserId: Number(user.sub),
        username: user.username || user.email,
        userRole: user.role,
        ...values,
        ipAddress: values.ipAddress || fallbackClientIp || null,
        clientIp: values.ipAddress || fallbackClientIp || null,
        errorMessage: values.errorReason
      }
    );
    await connection.commit();
    return { ok: true, source: values.source, status: values.status };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    await connection.close();
  }
}

export async function getClientConnectivityHistory(filters: ClientConnectivityFilters = {}) {
  return { data: await queryHistory(filters) };
}

export async function getMyClientConnectivityHistory(user: JwtPayload, filters: ClientConnectivityFilters = {}) {
  return { data: await queryHistory(filters, Number(user.sub)) };
}

export async function getClientConnectivitySummary(filters: ClientConnectivityFilters = {}) {
  void filters;
  return getClientAgentSummary();
}

export async function getClientConnectivityClients(filters: ClientConnectivityFilters = {}) {
  const rows = await queryHistory(filters);
  const clients = new Map<string, ReturnType<typeof mapRow>>();
  for (const row of rows.filter((item) => item.source === "OPSCENTER_AGENT")) {
    const key = row.clientId || row.hostname || row.username;
    if (key && !clients.has(key)) clients.set(key, row);
  }
  return { data: Array.from(clients.values()) };
}

export async function getClientConnectivityIncidents(filters: ClientConnectivityFilters = {}) {
  const rows = await queryHistory(filters);
  return {
    data: rows.filter((row) => row.status !== "ONLINE" && row.status !== "SLOW" && row.status !== "CANNOT_VERIFY")
  };
}
