import { getConnection } from "../config/database";
import { HttpError } from "../utils/httpError";
import { defaultSystemSettings } from "./settings.service";
import { writeAuditLog } from "./audit.service";
import oracledb from "oracledb";

export type InfrastructureService = {
  id: string;
  name: string;
  url: string;
  category: string;
  description: string;
  supportTeam: string;
  contactNumber: string;
  supportEmail: string;
  escalationNote: string;
  monitoringEnabled: boolean;
  isDefault: boolean;
  createdAt: string | null;
  updatedAt: string | null;
};

export type CustomInfrastructureServiceInput = {
  name?: unknown;
  url?: unknown;
  category?: unknown;
  description?: unknown;
  supportTeam?: unknown;
  contactNumber?: unknown;
  supportEmail?: unknown;
  escalationNote?: unknown;
  monitoringEnabled?: unknown;
};

export const defaultInfrastructureServiceDefinitions: InfrastructureService[] = [
  {
    id: "hpep-intranet",
    name: "HPEP Intranet",
    url: defaultSystemSettings.infrastructure.hpepIntranetUrl,
    category: "Intranet",
    description: "Default enterprise intranet service.",
    supportTeam: "IT Network Team",
    contactNumber: "",
    supportEmail: "",
    escalationNote: "Contact IT Network Team if HPEP Intranet is slow, offline, or down.",
    monitoringEnabled: true,
    isDefault: true,
    createdAt: null,
    updatedAt: null
  },
  {
    id: "bhel-webmail",
    name: "BHEL Webmail",
    url: defaultSystemSettings.infrastructure.bhelWebmailUrl,
    category: "Email",
    description: "Default enterprise webmail service.",
    supportTeam: "Mail/Admin Team",
    contactNumber: "",
    supportEmail: "",
    escalationNote: "Contact Mail/Admin Team if BHEL Webmail is slow, offline, or down.",
    monitoringEnabled: true,
    isDefault: true,
    createdAt: null,
    updatedAt: null
  },
  {
    id: "network-health",
    name: "Network Health",
    url: "internal://network-health",
    category: "Network",
    description: "Default network connectivity probe.",
    supportTeam: "Network Team",
    contactNumber: "",
    supportEmail: "",
    escalationNote: "Contact Network Team if network health is degraded or critical.",
    monitoringEnabled: true,
    isDefault: true,
    createdAt: null,
    updatedAt: null
  }
];

function toBool(value: unknown, fallback = true) {
  if (typeof value === "boolean") return value;
  if (value === "true" || value === "1" || value === 1) return true;
  if (value === "false" || value === "0" || value === 0) return false;
  return fallback;
}

function normalizeUrl(url: string) {
  return url.trim();
}

function validateUrl(url: string) {
  return /^https?:\/\//i.test(url);
}

function sanitizeInput(input: CustomInfrastructureServiceInput) {
  const name = String(input.name || "").trim().slice(0, 160);
  const url = normalizeUrl(String(input.url || "")).slice(0, 500);
  if (!name) throw new HttpError(400, "Service name is required.");
  if (!url) throw new HttpError(400, "URL is required.");
  if (!validateUrl(url)) throw new HttpError(400, "URL must start with http:// or https://.");
  return {
    name,
    url,
    category: String(input.category || "Custom").trim().slice(0, 120) || "Custom",
    description: String(input.description || "").trim().slice(0, 1000),
    supportTeam: String(input.supportTeam || "").trim().slice(0, 160),
    contactNumber: String(input.contactNumber || "").trim().slice(0, 80),
    supportEmail: String(input.supportEmail || "").trim().slice(0, 160),
    escalationNote: String(input.escalationNote || "").trim().slice(0, 1000),
    monitoringEnabled: toBool(input.monitoringEnabled, true)
  };
}

function sanitizeSupportInput(input: CustomInfrastructureServiceInput) {
  return {
    supportTeam: String(input.supportTeam || "").trim().slice(0, 160),
    contactNumber: String(input.contactNumber || "").trim().slice(0, 80),
    supportEmail: String(input.supportEmail || "").trim().slice(0, 160),
    escalationNote: String(input.escalationNote || "").trim().slice(0, 1000)
  };
}

export async function ensureInfrastructureServicesTable(connection: any) {
  const result = await connection.execute(
    `SELECT COUNT(*) AS count FROM user_tables WHERE table_name = 'INFRASTRUCTURE_SERVICES'`
  );
  const exists = Number(((result.rows || [])[0] as { COUNT?: number })?.COUNT || 0) > 0;
  if (exists) {
    await ensureInfrastructureServicesColumns(connection);
    await ensureInfrastructureServiceSupportTable(connection);
    return;
  }

  await connection.execute(
    `CREATE TABLE infrastructure_services (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      service_name VARCHAR2(160) NOT NULL,
      service_url VARCHAR2(500) NOT NULL,
      category VARCHAR2(120),
      description VARCHAR2(1000),
      support_team VARCHAR2(160),
      contact_number VARCHAR2(80),
      support_email VARCHAR2(160),
      escalation_note VARCHAR2(1000),
      monitoring_enabled NUMBER(1) DEFAULT 1 NOT NULL,
      is_default NUMBER(1) DEFAULT 0 NOT NULL,
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      CONSTRAINT chk_infra_services_custom CHECK (is_default = 0)
    )`
  );
  await connection.execute(`CREATE UNIQUE INDEX ux_infra_services_url ON infrastructure_services(LOWER(service_url))`);
  await ensureInfrastructureServiceSupportTable(connection);
}

async function ensureInfrastructureServicesColumns(connection: any) {
  const result = await connection.execute(
    `SELECT column_name FROM user_tab_columns WHERE table_name = 'INFRASTRUCTURE_SERVICES'`
  );
  const columns = new Set(((result.rows || []) as Array<{ COLUMN_NAME: string }>).map((row) => row.COLUMN_NAME));
  const additions: Array<[string, string]> = [
    ["SUPPORT_TEAM", "support_team VARCHAR2(160)"],
    ["CONTACT_NUMBER", "contact_number VARCHAR2(80)"],
    ["SUPPORT_EMAIL", "support_email VARCHAR2(160)"],
    ["ESCALATION_NOTE", "escalation_note VARCHAR2(1000)"]
  ];
  for (const [column, ddl] of additions) {
    if (!columns.has(column)) {
      await connection.execute(`ALTER TABLE infrastructure_services ADD (${ddl})`);
    }
  }
}

async function ensureInfrastructureServiceSupportTable(connection: any) {
  const result = await connection.execute(
    `SELECT COUNT(*) AS count FROM user_tables WHERE table_name = 'INFRASTRUCTURE_SERVICE_SUPPORT'`
  );
  const exists = Number(((result.rows || [])[0] as { COUNT?: number })?.COUNT || 0) > 0;
  if (exists) return;

  await connection.execute(
    `CREATE TABLE infrastructure_service_support (
      service_id VARCHAR2(80) PRIMARY KEY,
      support_team VARCHAR2(160),
      contact_number VARCHAR2(80),
      support_email VARCHAR2(160),
      escalation_note VARCHAR2(1000),
      updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`
  );
}

function mapRow(row: Record<string, any>): InfrastructureService {
  return {
    id: String(row.ID),
    name: row.SERVICE_NAME,
    url: row.SERVICE_URL,
    category: row.CATEGORY || "Custom",
    description: row.DESCRIPTION || "",
    supportTeam: row.SUPPORT_TEAM || "",
    contactNumber: row.CONTACT_NUMBER || "",
    supportEmail: row.SUPPORT_EMAIL || "",
    escalationNote: row.ESCALATION_NOTE || "",
    monitoringEnabled: Number(row.MONITORING_ENABLED) === 1,
    isDefault: Number(row.IS_DEFAULT) === 1,
    createdAt: row.CREATED_AT || null,
    updatedAt: row.UPDATED_AT || null
  };
}

async function readCustomServices(connection: any) {
  await ensureInfrastructureServicesTable(connection);
  const result = await connection.execute(
    `SELECT id, service_name, service_url, category, description,
            support_team, contact_number, support_email, escalation_note,
            monitoring_enabled, is_default, created_at, updated_at
     FROM infrastructure_services
     WHERE is_default = 0
     ORDER BY created_at ASC, id ASC`
  );
  return ((result.rows || []) as Array<Record<string, any>>).map(mapRow);
}

async function readSupportOverrides(connection: any) {
  await ensureInfrastructureServiceSupportTable(connection);
  const result = await connection.execute(
    `SELECT service_id, support_team, contact_number, support_email, escalation_note
     FROM infrastructure_service_support`
  );
  return new Map(((result.rows || []) as Array<Record<string, any>>).map((row) => [
    String(row.SERVICE_ID),
    {
      supportTeam: row.SUPPORT_TEAM || "",
      contactNumber: row.CONTACT_NUMBER || "",
      supportEmail: row.SUPPORT_EMAIL || "",
      escalationNote: row.ESCALATION_NOTE || ""
    }
  ]));
}

export async function getDefaultInfrastructureServicesWithSupport(connection: any) {
  const overrides = await readSupportOverrides(connection);
  return defaultInfrastructureServiceDefinitions.map((service) => ({
    ...service,
    ...(overrides.get(service.id) || {})
  }));
}

async function assertUrlUnique(connection: any, url: string, exceptId?: string) {
  const normalized = url.toLowerCase();
  const defaultDuplicate = defaultInfrastructureServiceDefinitions.some((service) => service.url.toLowerCase() === normalized);
  if (defaultDuplicate) throw new HttpError(409, "A service with this URL already exists.");

  const result = await connection.execute(
    `SELECT COUNT(*) AS count
     FROM infrastructure_services
     WHERE LOWER(service_url) = :url
       AND (:exceptId IS NULL OR id <> TO_NUMBER(:exceptId))`,
    { url: normalized, exceptId: exceptId || null }
  );
  const count = Number(((result.rows || [])[0] as { COUNT?: number })?.COUNT || 0);
  if (count > 0) throw new HttpError(409, "A service with this URL already exists.");
}

export async function getInfrastructureServices(options: { includeDefaults?: boolean } = { includeDefaults: true }) {
  const connection = await getConnection();
  try {
    const custom = await readCustomServices(connection);
    return {
      data: options.includeDefaults === false
        ? custom
        : [...(await getDefaultInfrastructureServicesWithSupport(connection)), ...custom]
    };
  } finally {
    await connection.close();
  }
}

export async function getCustomInfrastructureServices(connection?: any) {
  if (connection) return readCustomServices(connection);
  const ownedConnection = await getConnection();
  try {
    return await readCustomServices(ownedConnection);
  } finally {
    await ownedConnection.close();
  }
}

export async function createInfrastructureService(input: { actorId: number; values: CustomInfrastructureServiceInput }) {
  const values = sanitizeInput(input.values);
  const connection = await getConnection();
  try {
    await ensureInfrastructureServicesTable(connection);
    await assertUrlUnique(connection, values.url);
    const result = await connection.execute(
      `INSERT INTO infrastructure_services (
         service_name, service_url, category, description,
         support_team, contact_number, support_email, escalation_note,
         monitoring_enabled, is_default
       )
       VALUES (
         :name, :url, :category, :description,
         :supportTeam, :contactNumber, :supportEmail, :escalationNote,
         :monitoringEnabled, 0
       )
       RETURNING id INTO :id`,
      {
        ...values,
        monitoringEnabled: values.monitoringEnabled ? 1 : 0,
        id: { dir: oracledb.BIND_OUT, type: oracledb.NUMBER }
      }
    );
    const id = String(result.outBinds?.id?.[0] || "");
    await writeAuditLog({ userId: input.actorId, action: "infrastructure_service_created", details: `${values.name} added.` }, connection);
    await connection.commit();
    const services = await readCustomServices(connection);
    return { data: services.find((service) => service.id === id) || services[services.length - 1] };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    await connection.close();
  }
}

export async function updateInfrastructureService(input: { actorId: number; id: string; values: CustomInfrastructureServiceInput }) {
  const defaultService = defaultInfrastructureServiceDefinitions.find((service) => service.id === input.id);
  if (defaultService) {
    const values = sanitizeSupportInput(input.values);
    const connection = await getConnection();
    try {
      await ensureInfrastructureServicesTable(connection);
      await connection.execute(
        `MERGE INTO infrastructure_service_support target
         USING (SELECT :serviceId AS service_id FROM dual) source
         ON (target.service_id = source.service_id)
         WHEN MATCHED THEN UPDATE SET
           support_team = :supportTeam,
           contact_number = :contactNumber,
           support_email = :supportEmail,
           escalation_note = :escalationNote,
           updated_at = CURRENT_TIMESTAMP
         WHEN NOT MATCHED THEN INSERT (
           service_id, support_team, contact_number, support_email, escalation_note
         ) VALUES (
           :serviceId, :supportTeam, :contactNumber, :supportEmail, :escalationNote
         )`,
        { serviceId: input.id, ...values }
      );
      await writeAuditLog({ userId: input.actorId, action: "infrastructure_service_support_updated", details: `${defaultService.name} support contact updated.` }, connection);
      await connection.commit();
      return { data: (await getDefaultInfrastructureServicesWithSupport(connection)).find((service) => service.id === input.id) };
    } catch (error) {
      await connection.rollback();
      throw error;
    } finally {
      await connection.close();
    }
  }
  const values = sanitizeInput(input.values);
  const connection = await getConnection();
  try {
    await ensureInfrastructureServicesTable(connection);
    await assertUrlUnique(connection, values.url, input.id);
    const result = await connection.execute(
      `UPDATE infrastructure_services
       SET service_name = :name,
           service_url = :url,
           category = :category,
           description = :description,
           support_team = :supportTeam,
           contact_number = :contactNumber,
           support_email = :supportEmail,
           escalation_note = :escalationNote,
           monitoring_enabled = :monitoringEnabled,
           updated_at = CURRENT_TIMESTAMP
       WHERE id = :id AND is_default = 0`,
      { ...values, monitoringEnabled: values.monitoringEnabled ? 1 : 0, id: input.id }
    );
    if (!result.rowsAffected) throw new HttpError(404, "Infrastructure service not found.");
    await writeAuditLog({ userId: input.actorId, action: "infrastructure_service_updated", details: `${values.name} updated.` }, connection);
    await connection.commit();
    const services = await readCustomServices(connection);
    return { data: services.find((service) => service.id === input.id) };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    await connection.close();
  }
}

export async function deleteInfrastructureService(input: { actorId: number; id: string }) {
  if (defaultInfrastructureServiceDefinitions.some((service) => service.id === input.id)) {
    throw new HttpError(403, "Default services cannot be deleted.");
  }
  const connection = await getConnection();
  try {
    await ensureInfrastructureServicesTable(connection);
    const result = await connection.execute(
      `DELETE FROM infrastructure_services WHERE id = :id AND is_default = 0`,
      { id: input.id }
    );
    if (!result.rowsAffected) throw new HttpError(404, "Infrastructure service not found.");
    await writeAuditLog({ userId: input.actorId, action: "infrastructure_service_deleted", details: `Infrastructure service ${input.id} deleted.` }, connection);
    await connection.commit();
    return { ok: true };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    await connection.close();
  }
}
