import { lookup } from "dns/promises";
import { getConnection } from "../config/database";
import { writeAuditLog } from "./audit.service";
import { notifyAdmins } from "./notification.service";
import { getSystemSettings, type SystemSettings } from "./settings.service";

type ServiceKey = "hpep-intranet" | "bhel-webmail" | "network-health";
type ServiceStatus = "healthy" | "online" | "slow" | "offline" | "unknown";
type RangeKey = "24h" | "7d" | "30d";

type ServiceDefinition = {
  key: Exclude<ServiceKey, "network-health">;
  name: string;
  url: string;
  onlineLabel: "Healthy" | "Online";
};

export type ServiceHealthSnapshot = {
  key: ServiceKey;
  serviceName: string;
  status: ServiceStatus;
  statusLabel: string;
  responseTimeMs: number | null;
  latencyMs: number | null;
  packetLossPercent: number | null;
  dnsStatus: string | null;
  dnsResponseTimeMs: number | null;
  lastCheckedAt: string;
  lastSuccessfulCheckAt: string | null;
  availability: string;
  availabilityPercent: number;
  incidentCount: number;
  message: string;
  internetStatus?: string;
  overallNetworkHealth?: string;
};

export type ServiceHealthHistoryPoint = {
  id: number;
  serviceKey: ServiceKey;
  serviceName: string;
  checkedAt: string;
  status: ServiceStatus;
  responseTimeMs: number | null;
  latencyMs: number | null;
  packetLossPercent: number | null;
  dnsStatus: string | null;
  dnsResponseTimeMs: number | null;
  availabilityPercent: number;
  errorMessage: string | null;
};

const previousStatus = new Map<ServiceKey, ServiceStatus>();
const lastSuccessfulChecks = new Map<ServiceKey, string>();
const networkProbeUrl = "https://www.google.com/generate_204";
const dnsProbeHost = "google.com";

function servicesFromSettings(settings: SystemSettings): ServiceDefinition[] {
  return [
    {
      key: "hpep-intranet",
      name: "HPEP Intranet",
      url: settings.infrastructure.hpepIntranetUrl,
      onlineLabel: "Healthy"
    },
    {
      key: "bhel-webmail",
      name: "BHEL Webmail",
      url: settings.infrastructure.bhelWebmailUrl,
      onlineLabel: "Online"
    }
  ];
}

function normalizeRange(range: unknown): RangeKey {
  return range === "7d" || range === "30d" ? range : "24h";
}

function rangeToInterval(range: string) {
  if (range === "7d") return "7";
  if (range === "30d") return "30";
  return "1";
}

function bucketFor(value: unknown, range: RangeKey) {
  const date = value instanceof Date ? value : new Date(String(value));
  if (Number.isNaN(date.getTime())) return "unknown";
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  if (range === "24h") {
    const hour = String(date.getHours()).padStart(2, "0");
    return `${year}-${month}-${day} ${hour}:00`;
  }
  return `${year}-${month}-${day}`;
}

function statusLabelFor(service: ServiceDefinition, status: ServiceStatus) {
  if (status === "healthy" || status === "online") return service.onlineLabel;
  if (status === "slow") return "Slow";
  if (status === "unknown") return "Cannot verify";
  return "Offline";
}

function availabilityFor(status: ServiceStatus) {
  if (status === "offline") return 0;
  if (status === "unknown") return 0;
  if (status === "slow") return 95;
  return 100;
}

function isIncident(status: ServiceStatus) {
  return status === "offline" || status === "slow" || status === "unknown";
}

async function ensureServiceHealthHistoryTable(connection: any) {
  const result = await connection.execute(
    `SELECT COUNT(*) AS count FROM user_tables WHERE table_name = 'SERVICE_HEALTH_HISTORY'`
  );
  const exists = Number(((result.rows || [])[0] as { COUNT?: number })?.COUNT || 0) > 0;
  if (exists) return;

  await connection.execute(
    `CREATE TABLE service_health_history (
      id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      service_key VARCHAR2(80) NOT NULL,
      service_name VARCHAR2(160) NOT NULL,
      checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
      status VARCHAR2(30) NOT NULL,
      response_time_ms NUMBER,
      latency_ms NUMBER,
      packet_loss_percent NUMBER(5,2),
      dns_status VARCHAR2(40),
      dns_response_time_ms NUMBER,
      availability_percent NUMBER(5,2),
      error_message VARCHAR2(1000),
      created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
    )`
  );
  await connection.execute(`CREATE INDEX idx_service_health_hist_key_time ON service_health_history(service_key, checked_at)`);
  await connection.commit();
}

async function recordOfflineTransition(connection: any, snapshot: ServiceHealthSnapshot) {
  const priorStatus = previousStatus.get(snapshot.key);
  previousStatus.set(snapshot.key, snapshot.status);
  if (!priorStatus || priorStatus === snapshot.status) return;

  const details = `${snapshot.serviceName} changed from ${priorStatus} to ${snapshot.status}. ${snapshot.message}`;
  await writeAuditLog({ action: "service_health_status_change", details }, connection);
  if (snapshot.status === "offline") {
    await notifyAdmins({
      title: `${snapshot.serviceName} Offline`,
      body: `${snapshot.serviceName} is unreachable. ${snapshot.message}`,
      category: "serviceOutage"
    }, connection);
  }
}

async function saveSnapshot(connection: any, snapshot: ServiceHealthSnapshot) {
  await ensureServiceHealthHistoryTable(connection);
  await connection.execute(
    `INSERT INTO service_health_history (
      service_key, service_name, checked_at, status, response_time_ms,
      latency_ms, packet_loss_percent, dns_status, dns_response_time_ms,
      availability_percent, error_message
    ) VALUES (
      :serviceKey, :serviceName, SYSTIMESTAMP, :status, :responseTimeMs,
      :latencyMs, :packetLossPercent, :dnsStatus, :dnsResponseTimeMs,
      :availabilityPercent, :errorMessage
    )`,
    {
      serviceKey: snapshot.key,
      serviceName: snapshot.serviceName,
      status: snapshot.status,
      responseTimeMs: snapshot.responseTimeMs,
      latencyMs: snapshot.latencyMs,
      packetLossPercent: snapshot.packetLossPercent,
      dnsStatus: snapshot.dnsStatus,
      dnsResponseTimeMs: snapshot.dnsResponseTimeMs,
      availabilityPercent: snapshot.availabilityPercent,
      errorMessage: snapshot.message || null
    }
  );
  await recordOfflineTransition(connection, snapshot);
}

async function getHistoryStats(connection: any, serviceKey: ServiceKey, range: RangeKey = "24h") {
  await ensureServiceHealthHistoryTable(connection);
  const result = await connection.execute(
    `SELECT
       COUNT(*) AS total,
       SUM(CASE WHEN status IN ('offline', 'slow', 'unknown') THEN 1 ELSE 0 END) AS incidents,
       AVG(CASE WHEN status IN ('healthy', 'online') THEN 100 ELSE 0 END) AS availability
     FROM service_health_history
     WHERE service_key = :serviceKey
       AND checked_at >= SYSTIMESTAMP - INTERVAL '${rangeToInterval(range)}' DAY`,
    { serviceKey }
  );
  const row = ((result.rows || [])[0] || {}) as Record<string, unknown>;
  const total = Number(row.TOTAL || 0);
  return {
    incidentCount: Number(row.INCIDENTS || 0),
    availabilityPercent: total ? Math.round(Number(row.AVAILABILITY || 0) * 100) / 100 : 100
  };
}

async function checkNetworkHealth(settings: SystemSettings): Promise<ServiceHealthSnapshot> {
  const checkedAt = new Date().toISOString();
  let dnsStatus = "Failed";
  let dnsResponseTimeMs: number | null = null;
  let internetStatus = "Offline";
  let status: ServiceStatus = "offline";
  let message = "Network unreachable";
  let latencyMs: number | null = null;

  const dnsStarted = Date.now();
  try {
    await lookup(dnsProbeHost);
    dnsResponseTimeMs = Date.now() - dnsStarted;
    dnsStatus = "Resolved";
  } catch {
    dnsResponseTimeMs = null;
  }

  const probes = await Promise.all(Array.from({ length: 4 }).map(async () => {
    const started = Date.now();
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), settings.infrastructure.timeoutThresholdMs);
    try {
      const response = await fetch(networkProbeUrl, { method: "GET", signal: controller.signal });
      return response.ok ? Date.now() - started : null;
    } catch {
      return null;
    } finally {
      clearTimeout(timeout);
    }
  }));

  const successfulProbes = probes.filter((probe): probe is number => probe !== null);
  const packetLossPercent = Math.round(((probes.length - successfulProbes.length) / probes.length) * 100);

  if (successfulProbes.length) {
    latencyMs = Math.round(successfulProbes.reduce((sum, probe) => sum + probe, 0) / successfulProbes.length);
    internetStatus = "Online";
    if (packetLossPercent === 0 && dnsStatus === "Resolved" && latencyMs < settings.infrastructure.slowResponseThresholdMs) {
      status = "healthy";
      message = "Network operating normally";
      lastSuccessfulChecks.set("network-health", checkedAt);
    } else if (packetLossPercent < settings.infrastructure.packetLossThresholdPercent && dnsStatus === "Resolved") {
      status = "slow";
      message = "Network degradation detected";
    } else {
      status = "offline";
      message = "Unstable network connectivity";
    }
  }

  return {
    key: "network-health",
    serviceName: "Network Health",
    status,
    statusLabel: status === "healthy" ? "Healthy" : status === "slow" ? "Degraded" : "Critical",
    responseTimeMs: latencyMs,
    latencyMs,
    packetLossPercent,
    dnsStatus,
    dnsResponseTimeMs,
    lastCheckedAt: checkedAt,
    lastSuccessfulCheckAt: lastSuccessfulChecks.get("network-health") || null,
    availability: `${availabilityFor(status)}%`,
    availabilityPercent: availabilityFor(status),
    incidentCount: 0,
    message,
    internetStatus,
    overallNetworkHealth: status === "healthy" ? "Healthy" : status === "slow" ? "Degraded" : "Critical"
  };
}

async function checkService(service: ServiceDefinition, network: ServiceHealthSnapshot, settings: SystemSettings): Promise<ServiceHealthSnapshot> {
  const checkedAt = new Date().toISOString();
  let responseTimeMs: number | null = null;
  let status: ServiceStatus = "offline";
  let message = service.key === "bhel-webmail" ? "Connection Failed" : "Connection Timeout";

  if (network.status === "offline") {
    status = "unknown";
    message = "Cannot verify - network unavailable";
  } else if (!service.url) {
    message = "Service URL not configured";
  } else {
    const started = Date.now();
    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), settings.infrastructure.timeoutThresholdMs);
    try {
      let response = await fetch(service.url, { method: "HEAD", signal: controller.signal });
      if (response.status === 405) {
        response = await fetch(service.url, { method: "GET", signal: controller.signal });
      }
      responseTimeMs = Date.now() - started;
      if (response.ok) {
        status = responseTimeMs < settings.infrastructure.slowResponseThresholdMs ? (service.onlineLabel === "Healthy" ? "healthy" : "online") : "slow";
        message = status === "slow" ? "Slow response detected" : "Service reachable";
        lastSuccessfulChecks.set(service.key, checkedAt);
      } else {
        message = `HTTP ${response.status}`;
      }
    } catch (error) {
      responseTimeMs = null;
      message = error instanceof Error && error.name === "AbortError"
        ? "Connection Timeout"
        : service.key === "bhel-webmail" ? "Connection Failed" : "Connection Timeout";
    } finally {
      clearTimeout(timeout);
    }
  }

  return {
    key: service.key,
    serviceName: service.name,
    status,
    statusLabel: statusLabelFor(service, status),
    responseTimeMs,
    latencyMs: null,
    packetLossPercent: null,
    dnsStatus: null,
    dnsResponseTimeMs: null,
    lastCheckedAt: checkedAt,
    lastSuccessfulCheckAt: lastSuccessfulChecks.get(service.key) || null,
    availability: `${availabilityFor(status)}%`,
    availabilityPercent: availabilityFor(status),
    incidentCount: 0,
    message
  };
}

function mapHistoryRow(row: Record<string, any>): ServiceHealthHistoryPoint {
  return {
    id: Number(row.ID),
    serviceKey: row.SERVICE_KEY,
    serviceName: row.SERVICE_NAME,
    checkedAt: row.CHECKED_AT,
    status: row.STATUS,
    responseTimeMs: row.RESPONSE_TIME_MS === null || row.RESPONSE_TIME_MS === undefined ? null : Number(row.RESPONSE_TIME_MS),
    latencyMs: row.LATENCY_MS === null || row.LATENCY_MS === undefined ? null : Number(row.LATENCY_MS),
    packetLossPercent: row.PACKET_LOSS_PERCENT === null || row.PACKET_LOSS_PERCENT === undefined ? null : Number(row.PACKET_LOSS_PERCENT),
    dnsStatus: row.DNS_STATUS || null,
    dnsResponseTimeMs: row.DNS_RESPONSE_TIME_MS === null || row.DNS_RESPONSE_TIME_MS === undefined ? null : Number(row.DNS_RESPONSE_TIME_MS),
    availabilityPercent: row.AVAILABILITY_PERCENT === null || row.AVAILABILITY_PERCENT === undefined ? 0 : Number(row.AVAILABILITY_PERCENT),
    errorMessage: row.ERROR_MESSAGE || null
  };
}

export async function getCurrentServiceHealth() {
  const connection = await getConnection();
  try {
    const settings = await getSystemSettings();
    await ensureServiceHealthHistoryTable(connection);
    const network = await checkNetworkHealth(settings);
    const serviceSnapshots = await Promise.all(servicesFromSettings(settings).map((service) => checkService(service, network, settings)));
    const snapshots = [...serviceSnapshots, network];

    for (const snapshot of snapshots) {
      await saveSnapshot(connection, snapshot);
    }
    await connection.commit();

    for (const snapshot of snapshots) {
      const stats = await getHistoryStats(connection, snapshot.key, "24h");
      snapshot.incidentCount = stats.incidentCount;
      snapshot.availabilityPercent = stats.availabilityPercent;
      snapshot.availability = `${stats.availabilityPercent}%`;
    }

    return { data: snapshots };
  } catch (error) {
    await connection.rollback();
    throw error;
  } finally {
    await connection.close();
  }
}

export async function getServiceHealthHistory(range: RangeKey = "24h") {
  const connection = await getConnection();
  try {
    await ensureServiceHealthHistoryTable(connection);
    const result = await connection.execute(
      `SELECT id, service_key, service_name, checked_at, status, response_time_ms,
              latency_ms, packet_loss_percent, dns_status, dns_response_time_ms,
              availability_percent, error_message
       FROM service_health_history
       WHERE checked_at >= SYSTIMESTAMP - INTERVAL '${rangeToInterval(range)}' DAY
       ORDER BY checked_at ASC`
    );
    return { data: ((result.rows || []) as Array<Record<string, any>>).map(mapHistoryRow) };
  } finally {
    await connection.close();
  }
}

export async function getServiceHealth() {
  return getCurrentServiceHealth();
}

export async function getInfrastructureCurrent() {
  return getCurrentServiceHealth();
}

export async function getInfrastructureHistory(inputRange: unknown = "24h") {
  return getServiceHealthHistory(normalizeRange(inputRange));
}

export async function getInfrastructureHeatmap(inputRange: unknown = "24h") {
  const range = normalizeRange(inputRange);
  const connection = await getConnection();
  try {
    await ensureServiceHealthHistoryTable(connection);
    const result = await connection.execute(
      `SELECT service_key, service_name, checked_at, status
       FROM service_health_history
       WHERE checked_at >= SYSTIMESTAMP - INTERVAL '${rangeToInterval(range)}' DAY
       ORDER BY service_key, checked_at`
    );

    const buckets = new Map<string, {
      serviceKey: ServiceKey;
      serviceName: string;
      bucket: string;
      totalChecks: number;
      healthyChecks: number;
      degradedChecks: number;
      criticalChecks: number;
    }>();

    for (const row of (result.rows || []) as Array<Record<string, any>>) {
      const serviceKey = row.SERVICE_KEY as ServiceKey;
      const bucket = bucketFor(row.CHECKED_AT, range);
      const key = `${serviceKey}:${bucket}`;
      const current = buckets.get(key) || {
        serviceKey,
        serviceName: String(row.SERVICE_NAME || serviceKey),
        bucket,
        totalChecks: 0,
        healthyChecks: 0,
        degradedChecks: 0,
        criticalChecks: 0
      };
      const status = String(row.STATUS || "");
      current.totalChecks += 1;
      if (status === "healthy" || status === "online") current.healthyChecks += 1;
      else if (status === "slow") current.degradedChecks += 1;
      else if (status === "offline" || status === "unknown") current.criticalChecks += 1;
      buckets.set(key, current);
    }

    const data = Array.from(buckets.values()).map((row) => {
      let status = "no_data";
      if (row.criticalChecks > 0) status = "critical";
      else if (row.degradedChecks > 0) status = "degraded";
      else if (row.healthyChecks > 0) status = "healthy";
      return {
        serviceKey: row.serviceKey,
        serviceName: row.serviceName,
        bucket: row.bucket,
        totalChecks: row.totalChecks,
        healthyChecks: row.healthyChecks,
        degradedChecks: row.degradedChecks,
        criticalChecks: row.criticalChecks,
        status
      };
    }).sort((left, right) => left.serviceKey.localeCompare(right.serviceKey) || left.bucket.localeCompare(right.bucket));

    return { data };
  } finally {
    await connection.close();
  }
}

export async function getInfrastructureIncidents(inputRange: unknown = "30d") {
  const range = normalizeRange(inputRange);
  const connection = await getConnection();
  try {
    await ensureServiceHealthHistoryTable(connection);
    const result = await connection.execute(
      `SELECT id, service_key, service_name, checked_at, status, response_time_ms,
              latency_ms, packet_loss_percent, dns_status, dns_response_time_ms,
              availability_percent, error_message,
              LAG(status) OVER (PARTITION BY service_key ORDER BY checked_at) AS previous_status
       FROM service_health_history
       WHERE checked_at >= SYSTIMESTAMP - INTERVAL '${rangeToInterval(range)}' DAY
       ORDER BY checked_at DESC`
    );

    const data = ((result.rows || []) as Array<Record<string, any>>)
      .filter((row) => {
        const status = String(row.STATUS || "");
        const previous = row.PREVIOUS_STATUS ? String(row.PREVIOUS_STATUS) : "";
        return isIncident(status as ServiceStatus) || (isIncident(previous as ServiceStatus) && (status === "healthy" || status === "online"));
      })
      .map((row) => {
        const status = String(row.STATUS || "");
        const previous = row.PREVIOUS_STATUS ? String(row.PREVIOUS_STATUS) : "";
        const recovered = isIncident(previous as ServiceStatus) && (status === "healthy" || status === "online");
        const type = recovered
          ? "Recovery"
          : status === "offline" || status === "unknown"
            ? "Service offline"
            : row.DNS_STATUS && String(row.DNS_STATUS).toLowerCase() !== "resolved"
              ? "DNS failure"
              : row.SERVICE_KEY === "network-health"
                ? "Network degraded"
                : "Slow response";
        return {
          id: Number(row.ID),
          serviceKey: row.SERVICE_KEY,
          serviceName: row.SERVICE_NAME,
          checkedAt: row.CHECKED_AT,
          status,
          previousStatus: previous || null,
          type,
          message: row.ERROR_MESSAGE || type,
          responseTimeMs: row.RESPONSE_TIME_MS === null || row.RESPONSE_TIME_MS === undefined ? null : Number(row.RESPONSE_TIME_MS),
          latencyMs: row.LATENCY_MS === null || row.LATENCY_MS === undefined ? null : Number(row.LATENCY_MS),
          packetLossPercent: row.PACKET_LOSS_PERCENT === null || row.PACKET_LOSS_PERCENT === undefined ? null : Number(row.PACKET_LOSS_PERCENT)
        };
      });

    return { data };
  } finally {
    await connection.close();
  }
}

export async function getInfrastructureReports(inputRange: unknown = "30d") {
  const range = normalizeRange(inputRange);
  const connection = await getConnection();
  try {
    await ensureServiceHealthHistoryTable(connection);
    const result = await connection.execute(
      `SELECT service_key, service_name,
              COUNT(*) AS total_checks,
              AVG(CASE WHEN status IN ('healthy', 'online') THEN 100 ELSE 0 END) AS availability_percent,
              AVG(NVL(response_time_ms, latency_ms)) AS average_response_time_ms,
              SUM(CASE WHEN status IN ('offline', 'unknown') THEN 1 ELSE 0 END) AS downtime_checks,
              SUM(CASE WHEN status IN ('offline', 'slow', 'unknown') THEN 1 ELSE 0 END) AS incident_count
       FROM service_health_history
       WHERE checked_at >= SYSTIMESTAMP - INTERVAL '${rangeToInterval(range)}' DAY
       GROUP BY service_key, service_name
       ORDER BY service_name`
    );

    const data = ((result.rows || []) as Array<Record<string, any>>).map((row) => {
      const downtimeChecks = Number(row.DOWNTIME_CHECKS || 0);
      return {
        serviceKey: row.SERVICE_KEY,
        serviceName: row.SERVICE_NAME,
        availabilityPercent: Math.round(Number(row.AVAILABILITY_PERCENT || 0) * 100) / 100,
        averageResponseTimeMs: row.AVERAGE_RESPONSE_TIME_MS === null || row.AVERAGE_RESPONSE_TIME_MS === undefined ? null : Math.round(Number(row.AVERAGE_RESPONSE_TIME_MS)),
        totalDowntimeMinutes: downtimeChecks,
        incidentCount: Number(row.INCIDENT_COUNT || 0),
        totalChecks: Number(row.TOTAL_CHECKS || 0)
      };
    });

    return { data };
  } finally {
    await connection.close();
  }
}
