CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(100) NOT NULL UNIQUE,
  full_name VARCHAR2(150) NOT NULL,
  email VARCHAR2(255) UNIQUE,
  password_hash VARCHAR2(255) NOT NULL,
  role VARCHAR2(20) CHECK (role IN ('employee', 'engineer', 'admin')) NOT NULL,
  department VARCHAR2(100),
  employee_id VARCHAR2(50) UNIQUE,
  phone VARCHAR2(20),
  status VARCHAR2(20) DEFAULT 'ACTIVE' NOT NULL,
  password_must_change NUMBER(1) DEFAULT 0 NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE password_reset_requests (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES users(id),
  username VARCHAR2(100) NOT NULL,
  requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
  processed_by NUMBER REFERENCES users(id),
  processed_at TIMESTAMP
);

CREATE TABLE assets (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  asset_tag VARCHAR2(80) NOT NULL UNIQUE,
  asset_name VARCHAR2(160) NOT NULL,
  category VARCHAR2(80) NOT NULL,
  type VARCHAR2(80) NOT NULL,
  brand VARCHAR2(120),
  model VARCHAR2(120),
  serial_number VARCHAR2(120) NOT NULL UNIQUE,
  status VARCHAR2(30) DEFAULT 'available' CHECK (status IN ('available', 'assigned', 'repair', 'retired')) NOT NULL,
  assigned_to NUMBER REFERENCES users(id),
  assigned_employee NUMBER REFERENCES users(id),
  department VARCHAR2(120),
  block VARCHAR2(80),
  room VARCHAR2(80),
  location VARCHAR2(160),
  purchase_date DATE,
  warranty_expiry DATE,
  processor VARCHAR2(120),
  ram VARCHAR2(80),
  storage VARCHAR2(120),
  operating_system VARCHAR2(120),
  lifecycle_state VARCHAR2(30) DEFAULT 'Available' NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE tickets (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR2(180) NOT NULL,
  description CLOB,
  category VARCHAR2(80) NOT NULL,
  subcategory VARCHAR2(120),
  priority VARCHAR2(20) CHECK (priority IN ('low', 'medium', 'high', 'critical')) NOT NULL,
  status VARCHAR2(30) DEFAULT 'open' CHECK (status IN ('open', 'assigned', 'in_progress', 'waiting_for_parts', 'escalated', 'resolved', 'closed')) NOT NULL,
  requester_id NUMBER NOT NULL REFERENCES users(id),
  assigned_to NUMBER REFERENCES users(id),
  asset_id NUMBER REFERENCES assets(id),
  department VARCHAR2(120),
  block VARCHAR2(80),
  room_number VARCHAR2(80),
  asset_tag_manual VARCHAR2(120),
  screenshot_url CLOB,
  service_image_url CLOB,
  engineer_notes CLOB,
  root_cause CLOB,
  corrective_action CLOB,
  preventive_action CLOB,
  parts_used CLOB,
  remarks CLOB,
  resolved_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE ticket_updates (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ticket_id NUMBER NOT NULL REFERENCES tickets(id) ON DELETE CASCADE,
  author_id NUMBER NOT NULL REFERENCES users(id),
  message CLOB NOT NULL,
  status_from VARCHAR2(30),
  status_to VARCHAR2(30),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE notifications (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  title VARCHAR2(160) NOT NULL,
  body VARCHAR2(1000),
  read_at TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE asset_requests (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  requester_id NUMBER NOT NULL REFERENCES users(id),
  asset_type VARCHAR2(80) NOT NULL,
  justification VARCHAR2(1000),
  status VARCHAR2(30) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'fulfilled')) NOT NULL,
  approved_by NUMBER REFERENCES users(id),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE audit_logs (
  id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id NUMBER REFERENCES users(id),
  action VARCHAR2(120) NOT NULL,
  details VARCHAR2(1000),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
