DECLARE
  PROCEDURE add_column_if_missing(p_table VARCHAR2, p_column VARCHAR2, p_definition VARCHAR2) IS
    v_count NUMBER;
  BEGIN
    SELECT COUNT(*) INTO v_count
    FROM user_tab_columns
    WHERE table_name = UPPER(p_table)
      AND column_name = UPPER(p_column);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE ' || p_table || ' ADD (' || p_column || ' ' || p_definition || ')';
    END IF;
  END;
BEGIN
  add_column_if_missing('tickets', 'subcategory', 'VARCHAR2(120)');
  add_column_if_missing('tickets', 'department', 'VARCHAR2(120)');
  add_column_if_missing('tickets', 'block', 'VARCHAR2(80)');
  add_column_if_missing('tickets', 'room_number', 'VARCHAR2(80)');
  add_column_if_missing('tickets', 'asset_tag_manual', 'VARCHAR2(120)');
  add_column_if_missing('tickets', 'screenshot_url', 'CLOB');
  add_column_if_missing('tickets', 'service_image_url', 'CLOB');
  add_column_if_missing('tickets', 'engineer_notes', 'CLOB');
  add_column_if_missing('tickets', 'root_cause', 'CLOB');
  add_column_if_missing('tickets', 'corrective_action', 'CLOB');
  add_column_if_missing('tickets', 'preventive_action', 'CLOB');
  add_column_if_missing('tickets', 'parts_used', 'CLOB');
  add_column_if_missing('tickets', 'remarks', 'CLOB');
  add_column_if_missing('tickets', 'resolved_at', 'TIMESTAMP');
END;
/

DECLARE
  v_constraint_name USER_CONSTRAINTS.CONSTRAINT_NAME%TYPE;
BEGIN
  SELECT uc.constraint_name
  INTO v_constraint_name
  FROM user_constraints uc
  JOIN user_cons_columns ucc ON ucc.constraint_name = uc.constraint_name
  WHERE uc.table_name = 'TICKETS'
    AND ucc.column_name = 'STATUS'
    AND uc.constraint_type = 'C'
  FETCH FIRST 1 ROWS ONLY;

  EXECUTE IMMEDIATE 'ALTER TABLE tickets DROP CONSTRAINT ' || v_constraint_name;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    NULL;
END;
/

ALTER TABLE tickets ADD CONSTRAINT chk_tickets_status
CHECK (status IN ('open', 'assigned', 'in_progress', 'waiting_for_parts', 'escalated', 'resolved', 'closed'));

DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_tables
  WHERE table_name = 'AUDIT_LOGS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE audit_logs (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER REFERENCES users(id),
        action VARCHAR2(120) NOT NULL,
        details VARCHAR2(1000),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_audit_logs_created ON audit_logs(created_at)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 THEN
      RAISE;
    END IF;
END;
/

COMMIT;
