DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM user_tables
  WHERE table_name = 'PASSWORD_RESET_REQUESTS';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE q'[
      CREATE TABLE password_reset_requests (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER NOT NULL REFERENCES users(id),
        username VARCHAR2(100) NOT NULL,
        requested_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        status VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
        processed_by NUMBER REFERENCES users(id),
        processed_at TIMESTAMP
      )
    ]';
  END IF;

  SELECT COUNT(*) INTO v_count
  FROM user_tab_columns
  WHERE table_name = 'USERS'
    AND column_name = 'PASSWORD_MUST_CHANGE';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE 'ALTER TABLE users ADD (password_must_change NUMBER(1) DEFAULT 0 NOT NULL)';
  END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_pwd_reset_user ON password_reset_requests(user_id)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 AND SQLCODE != -1408 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'CREATE INDEX idx_pwd_reset_status ON password_reset_requests(status, requested_at)';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -955 AND SQLCODE != -1408 THEN
      RAISE;
    END IF;
END;
/

COMMIT;
