DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*)
  INTO v_count
  FROM user_tables
  WHERE table_name = 'SERVICE_HEALTH_HISTORY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE service_health_history (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        service_key VARCHAR2(80) NOT NULL,
        service_name VARCHAR2(160) NOT NULL,
        checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        status VARCHAR2(30) NOT NULL,
        response_time_ms NUMBER,
        latency_ms NUMBER,
        packet_loss_percent NUMBER(5,2),
        dns_status VARCHAR2(40),
        dns_response_time_ms NUMBER,
        availability_percent NUMBER(5,2),
        error_message VARCHAR2(1000),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_service_health_hist_key_time ON service_health_history(service_key, checked_at)';
  END IF;
END;
/
