DECLARE
  v_count NUMBER;

  PROCEDURE add_column_if_missing(p_name VARCHAR2, p_definition VARCHAR2) IS
  BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tab_columns
     WHERE table_name = 'CLIENT_CONNECTIVITY_HISTORY'
       AND column_name = UPPER(p_name);

    IF v_count = 0 THEN
      EXECUTE IMMEDIATE 'ALTER TABLE client_connectivity_history ADD ' || p_definition;
    END IF;
  END;
BEGIN
  SELECT COUNT(*)
    INTO v_count
    FROM user_tables
   WHERE table_name = 'CLIENT_CONNECTIVITY_HISTORY';

  IF v_count = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE client_connectivity_history (
        id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        user_id NUMBER,
        username VARCHAR2(160),
        user_role VARCHAR2(40),
        client_id VARCHAR2(160),
        hostname VARCHAR2(255),
        ip_address VARCHAR2(80),
        reported_user_id VARCHAR2(160),
        department VARCHAR2(160),
        block VARCHAR2(160),
        checked_from VARCHAR2(80) DEFAULT ''Browser Check'' NOT NULL,
        source VARCHAR2(40) DEFAULT ''BROWSER_CHECK'' NOT NULL,
        service_name VARCHAR2(160) NOT NULL,
        service_type VARCHAR2(60),
        service_url VARCHAR2(1000),
        target_url VARCHAR2(500),
        status VARCHAR2(30) NOT NULL,
        response_time_ms NUMBER,
        packet_loss NUMBER(7,2),
        dns_status VARCHAR2(40),
        error_reason VARCHAR2(1000),
        checked_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
        browser_info VARCHAR2(1000),
        client_ip VARCHAR2(80),
        error_message VARCHAR2(1000),
        created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
      )';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_client_conn_hist_user_time ON client_connectivity_history(user_id, checked_at)';
    EXECUTE IMMEDIATE 'CREATE INDEX idx_client_conn_hist_filters ON client_connectivity_history(source, status, service_name, checked_at)';
  ELSE
    add_column_if_missing('CLIENT_ID', 'client_id VARCHAR2(160)');
    add_column_if_missing('HOSTNAME', 'hostname VARCHAR2(255)');
    add_column_if_missing('IP_ADDRESS', 'ip_address VARCHAR2(80)');
    add_column_if_missing('REPORTED_USER_ID', 'reported_user_id VARCHAR2(160)');
    add_column_if_missing('DEPARTMENT', 'department VARCHAR2(160)');
    add_column_if_missing('BLOCK', 'block VARCHAR2(160)');
    add_column_if_missing('CHECKED_FROM', 'checked_from VARCHAR2(80) DEFAULT ''Browser Check'' NOT NULL');
    add_column_if_missing('SOURCE', 'source VARCHAR2(40) DEFAULT ''BROWSER_CHECK'' NOT NULL');
    add_column_if_missing('SERVICE_URL', 'service_url VARCHAR2(1000)');
    add_column_if_missing('PACKET_LOSS', 'packet_loss NUMBER(7,2)');
    add_column_if_missing('DNS_STATUS', 'dns_status VARCHAR2(40)');
    add_column_if_missing('ERROR_REASON', 'error_reason VARCHAR2(1000)');
    add_column_if_missing('CREATED_AT', 'created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL');
  END IF;
END;
/
